### ISSUE TITLE
Ancho de la página es scrolleable

### ISSUE THREAD

**Issue by pechitook** [GraphqlBA/oradorapp#6]
La regla `margin: -1em;` en `SpeakerList` hace que el ancho de la página se exceda. Como no se qué querías hacer con eso, en lugar de proponer un fix (borrar la regla) te creo el issue para que lo manejes vos @leoasis 😘

**Comment by leoasis** [comment]
La idea era hacer que el `SpeakerList` tenga padding entre sus elementos, pero no en los bordes (es decir, que ocupe todo el espacio que le da el contenedor). Lo que falta es que el contenido de la pagina tenga un padding desde el borde para que ese margen negativo lo cancele pero aun no se exceda de la pagina. Ahora mando un PR donde arreglo esto
